# .coderabbit.yaml
language: 'en-US'
early_access: false

reviews:
  profile: 'chill'
  request_changes_workflow: false
  high_level_summary: true
  path_filters:
    - '!package-lock.json'
    - '!dist/**'
    - '!node_modules/**'
    - '!*.svg'
    - '!public/**'
  auto_review:
    enabled: true
    drafts: false

chat:
  auto_reply: true
